### ISSUE TITLE
Config file for reproducing results for meta-gru-res

### ISSUE THREAD

**Issue by yardenas** [john-x-jiang/meta_ssm#1]
Hi!

Thanks for the awesome work :)

Few things that didn't click for me:
* `main.py` scripts points at `b01` config, which does not exist in the repository. Can you share some info on how to replicate your results for `meta-gru-res` on the bouncing ball task?
* I don't understand is why in all of the `self.domain_function = ...` initializations you set the `stochastic` flag as `False`. I'd assume we need to sample a context for (approximate) variational inference 
* My understanding is that [this](https://github.com/john-x-jiang/meta_ssm/blob/bfd977bc58219686c132375056587006692fb3a2/model/model.py#L229) line computes the posterior. I'd expect the dynamics and emission predictions to be conditioned on a sample from this posterior, but it seems like it's conditioned on the prior, what am I missing here?

Cheers

**Comment by john-x-jiang** [comment]
Hi,

Thank you for your questions. Regarding your points:

1. I've uploaded two reference configurations in `config/`. Please check them and find the detail.
2. Sorry for the confusion. The `stochastic` flag was never used in the domain function. The `self.domain_function` was used to get the latent embedding of each sample in the context set, which is the $h_{\phi}(\cdot)$ in the paper. The stochastic domain embedding was then obtained by the function starting at line 185 in `model.py`.
3. Your understanding is correct. In theory, we assume that the posterior and the prior should be similar, and the condition should be on the posterior. That means conditioning on both distributions should be similar if the assumption is true. Practically, conditioning on the prior would be harder to obtain and more similar to the testing time, because there would be no full sequence of query samples. If conditioning on the prior works, we believe that it should also work with conditioning on the posterior. Please feel free to try that if you get any chance for implementation.

Thanks

**Comment by yardenas** [comment]
Thanks for the answers!

**Comment by WonderSeven** [comment]
Hi, there

Thanks for your wonderful work. I found a little mismatch between the uploaded configuration file and current code version, so I updated the config file [bouncingball.json](https://github.com/john-x-jiang/meta_ssm/files/13405938/bouncingball.json) for prompt usage.

Furthermore, I want to inquire about why the training stage uses $c$ coming from the prior $p_\zeta(c|D^s_j)$ rather than the posterior $q_\zeta(c|D^s_j \cup x^q_{0:T})$? Is there a specific reason or consideration for this choice?

Kind regards

**Comment by john-x-jiang** [comment]
Thank you for your question. 

Regarding the configuration file, yes. I believe you are referring to the data loader and your update is correct.

Regarding the sampling of $c$, we have a detailed explanation in one of the earlier questions: In theory, we assume that the posterior and the prior should be similar, and the condition should be on the posterior. That means conditioning on both distributions should be similar if the assumption is true. Practically, conditioning on the prior would be harder to obtain and more similar to the testing time, because there would be no full sequence of query samples. If conditioning on the prior works, we believe that it should also work with conditioning on the posterior. Please feel free to try that if you get any chance for implementation.

Thanks!

**Comment by WonderSeven** [comment]
Indeed, training based on prior maintains a similar setup as the test stage, this may improve the results to some degree. Thank you very much for your thoughtful response, this solves my question. 

Regards
